import { Role, Permission } from "@/lib/types";

export const BASE_SYSTEM_ROLES: Role[] = [
  {
    id: "b1000000-0000-4000-b000-000000000001",
    org_id: "demo-org-1",
    name: "SuperAdministrador",
    slug: "super_admin",
    description: "Acceso irrestricto total al sistema y gestión de configuración raíz.",
    hierarchy_level: 0,
    is_system: true,
  },
  {
    id: "b1000000-0000-4000-b000-000000000002",
    org_id: "demo-org-1",
    name: "Administrador",
    slug: "admin",
    description: "Administración de usuarios, roles, políticas y grupos.",
    hierarchy_level: 1,
    is_system: true,
  },
  {
    id: "b1000000-0000-4000-b000-000000000003",
    org_id: "demo-org-1",
    name: "Gerente",
    slug: "manager",
    description: "Gestión operativa departamental, comunicados y aprobaciones.",
    hierarchy_level: 2,
    is_system: true,
  },
  {
    id: "b1000000-0000-4000-b000-000000000004",
    org_id: "demo-org-1",
    name: "Usuario",
    slug: "employee",
    description: "Acceso estándar a autoservicio, chat, directorio y documentos.",
    hierarchy_level: 3,
    is_system: true,
  },
];

export const SYSTEM_PERMISSIONS: Permission[] = [
  { id: "p1", resource: "users", action: "create", description: "Crear nuevos colaboradores" },
  { id: "p2", resource: "users", action: "read", description: "Consultar perfiles de colaboradores" },
  { id: "p3", resource: "users", action: "update", description: "Editar datos de colaboradores" },
  { id: "p4", resource: "users", action: "delete", description: "Dar de baja colaboradores" },
  { id: "p5", resource: "roles", action: "create", description: "Crear roles personalizados" },
  { id: "p6", resource: "roles", action: "read", description: "Visualizar catálogo de roles y permisos" },
  { id: "p7", resource: "roles", action: "update", description: "Modificar matrices de permisos" },
  { id: "p8", resource: "roles", action: "delete", description: "Eliminar roles personalizados" },
  { id: "p9", resource: "roles", action: "assign", description: "Asignar roles a usuarios" },
  { id: "p10", resource: "groups", action: "create", description: "Crear grupos de usuarios" },
  { id: "p11", resource: "groups", action: "read", description: "Consultar grupos de la organización" },
  { id: "p12", resource: "groups", action: "update", description: "Editar grupos" },
  { id: "p13", resource: "groups", action: "delete", description: "Eliminar grupos" },
  { id: "p14", resource: "groups", action: "assign", description: "Asignar colaboradores a grupos" },
  { id: "p15", resource: "announcements", action: "create", description: "Redactar comunicados" },
  { id: "p16", resource: "announcements", action: "read", description: "Leer comunicados" },
  { id: "p17", resource: "announcements", action: "update", description: "Editar comunicados" },
  { id: "p18", resource: "announcements", action: "delete", description: "Eliminar comunicados" },
  { id: "p19", resource: "announcements", action: "publish", description: "Publicar comunicados urgentes" },
  { id: "p20", resource: "knowledge", action: "create", description: "Subir artículos y SOPs" },
  { id: "p21", resource: "knowledge", action: "read", description: "Consultar base de conocimiento" },
  { id: "p22", resource: "knowledge", action: "update", description: "Actualizar versiones de documentos" },
  { id: "p23", resource: "knowledge", action: "delete", description: "Archivar documentos" },
  { id: "p24", resource: "payroll", action: "read:self", description: "Consultar recibos propios" },
  { id: "p25", resource: "payroll", action: "read:all", description: "Consultar recibos de toda la plantilla" },
  { id: "p26", resource: "payroll", action: "import", description: "Importar timbrados CONTPAQi/NOI" },
  { id: "p27", resource: "attendance", action: "checkin:self", description: "Registrar asistencia propia" },
  { id: "p28", resource: "attendance", action: "read:department", description: "Ver asistencias de departamento" },
  { id: "p29", resource: "attendance", action: "read:all", description: "Ver asistencias globales" },
  { id: "p30", resource: "attendance", action: "import", description: "Importar registros biométricos" },
  { id: "p31", resource: "projects", action: "create", description: "Crear espacios de proyecto" },
  { id: "p32", resource: "projects", action: "read", description: "Ver espacios de proyecto" },
  { id: "p33", resource: "projects", action: "update", description: "Modificar hitos y acuerdos" },
];
